version: '3.8'

services:
  furniture-shop:
    image: tomcat:9.0.104-jdk21
    ports:
      - "8080:8080"
    volumes:
      - ./target/FurnitureShop_11_11_14h-1.0.war:/usr/local/tomcat/webapps/ROOT.war
    restart: unless-stopped
